# Generated by Django 4.2 on 2023-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0015_notifications_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
