# Generated by Django 4.2 on 2023-05-16 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nemo', '0016_notifications_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.notifications')),
                ('readuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
