# Generated by Django 4.2 on 2023-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0017_readnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='added_by_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
