# Generated by Django 4.2 on 2023-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0019_crewplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewplanner',
            name='crew_updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
