# Generated by Django 4.2 on 2023-05-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nemo', '0020_crewplanner_crew_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewplanner',
            name='crew_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
