# Generated by Django 4.2 on 2023-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0021_alter_crewplanner_crew_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
