# Generated by Django 4.2 on 2023-05-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0025_notifications_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
