# Generated by Django 4.2 on 2023-05-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0029_rename_date_rem_candidate_birth_remainder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='birth_remainder',
            new_name='remainder',
        ),
    ]
