# Generated by Django 4.2 on 2023-05-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0030_rename_birth_remainder_candidate_remainder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='remainder',
        ),
    ]
