# Generated by Django 4.2 on 2023-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0031_remove_candidate_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth_month',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
