# Generated by Django 4.2 on 2023-06-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0036_alter_documenttype_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='document_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
