# Generated by Django 4.2 on 2023-06-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0038_candidate_group_candidate_user_candidate_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='group',
        ),
    ]
