# Generated by Django 4.2 on 2023-06-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0039_remove_candidate_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='group',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
