# Generated by Django 4.2 on 2023-06-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0040_candidate_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='group',
            new_name='team',
        ),
    ]
