# Generated by Django 4.2 on 2023-06-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0042_rename_status_candidate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='active',
            field=models.CharField(max_length=200),
        ),
    ]
