# Generated by Django 4.2 on 2023-06-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0043_alter_candidate_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='active',
            new_name='status',
        ),
    ]
