# Generated by Django 4.2 on 2023-06-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0045_remove_candidate_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='vendor',
        ),
    ]
