# Generated by Django 4.2 on 2023-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0047_remove_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN-ACTIVE', 'IN-ACTIVE')], max_length=200),
        ),
    ]
