# Generated by Django 4.2 on 2023-06-02 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nemo', '0051_candidate_vendor_alter_candidate_added_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='added_by_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vendor',
            field=models.CharField(max_length=200),
        ),
    ]
