# Generated by Django 4.2 on 2023-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0052_alter_candidate_added_by_user_alter_candidate_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='added_by_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
