# Generated by Django 4.2 on 2023-06-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0053_alter_candidate_added_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewplanner',
            name='crew_immediate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
    ]
