# Generated by Django 4.2 on 2023-06-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0055_alter_crewplanner_crew_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewplanner',
            name='crew_rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
