# Generated by Django 4.2 on 2023-06-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0060_medical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical',
        ),
    ]
