# Generated by Django 4.2 on 2023-06-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0063_rename_group_candidate_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.CharField(max_length=200, null=True)),
                ('travel_from', models.CharField(max_length=200, null=True)),
                ('travel_to', models.CharField(max_length=200, null=True)),
                ('travel_mode', models.CharField(choices=[('BUS', 'BUS'), ('TRAIN', 'TRAIN'), ('AIR', 'AIR'), ('CAB', 'CAB')], max_length=200, null=True)),
                ('travel_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('CANCELLED', 'CANCELLED'), ('TRAVELLING', 'TRAVELLING'), ('TRAVELLED', 'TRAVELLED')], max_length=200, null=True)),
                ('ticket_no', models.CharField(max_length=200, null=True)),
                ('agent_name', models.CharField(max_length=200, null=True)),
                ('travel_amount', models.CharField(max_length=200, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.candidate')),
                ('port_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.portagent')),
            ],
        ),
    ]
