# Generated by Django 4.2 on 2023-06-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0064_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('INDIAN', 'INDIAN'), ('NRI', 'NRI')], max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('Account_no', models.CharField(max_length=200, null=True)),
                ('bank_address', models.CharField(max_length=200, null=True)),
                ('ifsc_code', models.CharField(max_length=200, null=True)),
                ('swift_code', models.CharField(max_length=200, null=True)),
                ('benificiary', models.CharField(max_length=200, null=True)),
                ('benificiary_address', models.CharField(max_length=200, null=True)),
                ('pancard_number', models.CharField(max_length=200, null=True)),
                ('statement', models.FileField(blank=True, max_length=200, upload_to='bankdetails')),
                ('pancard', models.FileField(blank=True, max_length=200, upload_to='bankdetails')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.candidate')),
            ],
        ),
    ]
