# Generated by Django 4.2 on 2023-06-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0066_rename_account_no_bankdetails_account_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=200, null=True)),
                ('document_number', models.CharField(max_length=200, null=True)),
                ('issue_date', models.CharField(max_length=200, null=True)),
                ('issue_place', models.CharField(max_length=200, null=True)),
                ('document_files', models.FileField(max_length=200, null=True, upload_to='document')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.candidate')),
            ],
        ),
    ]
