# Generated by Django 4.2 on 2023-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0067_candidatedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateNkd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('kin_relation', models.CharField(choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('HUSBAND', 'HUSBAND'), ('WIFE', 'WIFE'), ('MOTHER-IN-LAW', 'MOTHER-IN-LAW'), ('FATHER-IN-LAW', 'FATHER-IN-LAW'), ('UNCLE', 'UNCLE'), ('AUNT', 'AUNT'), ('NEPHEW', 'NEPHEW'), ('NIECE', 'NIECE')], max_length=200, null=True)),
                ('kin_contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('kin_contact_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='document_files',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='document'),
        ),
    ]
