# Generated by Django 4.2 on 2023-06-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0068_candidatenkd_alter_candidatedocument_document_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatenkd',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nemo.candidate'),
        ),
    ]
