# Generated by Django 4.2 on 2023-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0069_candidatenkd_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatenkd',
            name='kin_priority',
            field=models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=200, null=True),
        ),
    ]
