# Generated by Django 4.2 on 2023-06-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0070_candidatenkd_kin_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsl_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sign_on', models.CharField(blank=True, max_length=200, null=True)),
                ('wage_start', models.CharField(blank=True, max_length=200, null=True)),
                ('eoc', models.CharField(blank=True, max_length=200, null=True)),
                ('wages', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, choices=[('AED', 'AED'), ('BMD', 'BMD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('MYR', 'MYR'), ('SGD', 'SGD'), ('USD', 'USD')], max_length=200, null=True)),
                ('wages_types', models.CharField(blank=True, choices=[('NETT', 'NETT'), ('GROSS', 'GROSS'), ('PER DAY', 'PER DAY'), ('PER MONTH', 'PER MONTH')], max_length=200, null=True)),
                ('sign_off', models.CharField(blank=True, max_length=200, null=True)),
                ('reason_for_sign_off', models.CharField(blank=True, max_length=200, null=True)),
                ('documents', models.FileField(blank=True, max_length=200, null=True, upload_to='contract')),
                ('aoa', models.FileField(blank=True, max_length=200, null=True, upload_to='contract')),
                ('aoa_number', models.CharField(blank=True, max_length=200, null=True)),
                ('emigrate_number', models.CharField(blank=True, max_length=200, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nemo.candidate')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nemo.company')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nemo.rank')),
                ('sign_on_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nemo.port')),
                ('vessel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nemo.vessel')),
            ],
        ),
    ]
