# Generated by Django 4.2 on 2023-06-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0071_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sign_off_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_off_port', to='nemo.port'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_on_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_on_port', to='nemo.port'),
        ),
    ]
