# Generated by Django 4.2 on 2023-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0073_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='comment_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='reference_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='reminder_check',
            field=models.BooleanField(default=False),
        ),
    ]
