# Generated by Django 4.2 on 2023-06-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0077_rename_rejected_discussion_reject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='rank',
            new_name='contract_rank',
        ),
    ]
