# Generated by Django 4.2 on 2023-06-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0078_rename_rank_contract_contract_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_rank',
            new_name='rank',
        ),
    ]
