# Generated by Django 4.2 on 2023-07-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0079_rename_contract_rank_contract_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='groups',
            new_name='candidate_groups',
        ),
    ]
