# Generated by Django 4.2 on 2023-09-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0080_rename_groups_candidate_candidate_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='count_birth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
